In [30]:
import torch

In [31]:
print(torch.__version__)

1.11.0


In [32]:
# starting with scaler 
scaler = torch.tensor(7)
scaler

tensor(7)

In [33]:
print(f'the data type: {scaler.dtype}')
print(f'the size: {scaler.size()}')
print(f'the shape: {scaler.shape}')
print(f'the number of dimentions of scaler: {scaler.ndim}')
print(f'the items: {scaler.item()}')

the data type: torch.int64
the size: torch.Size([])
the shape: torch.Size([])
the number of dimentions of scaler: 0
the items: 7


## vectors 

`vectors` are abstract entities which may or may not be characterized by a magnitude and a direction.
we can present the vector as a tensor 

In [34]:
vector = torch.tensor((5,5))
vector

tensor([5, 5])

In [35]:
print(f'the data type: {vector.dtype}')
print(f'the size: {vector.size()}')
print(f'the shape: {vector.shape}')
print(f'the number of dimentions of vector: {vector.ndim}')

the data type: torch.int64
the size: torch.Size([2])
the shape: torch.Size([2])
the number of dimentions of vector: 1


In [36]:
vector = torch.tensor([[4,4],
                      [5,5]])

In [37]:
print(f'the # of dimentions of the vector is : {vector.ndim}')

the # of dimentions of the vector is : 2


# Random tensor

In [38]:
rand_tens = torch.rand(224,224,3)
rand_tens.dtype , rand_tens.shape , rand_tens.ndim

(torch.float32, torch.Size([224, 224, 3]), 3)

## zeros and ones

In [39]:
zeros = torch.zeros(5,5)
zeros , zeros.dtype

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.float32)

In [40]:
ones = torch.ones(size = (5,5))
ones  , ones.dtype

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.float32)

# range and tensor 

we can use `torch.arange(start , end , step`)

Where:

*  `start` = start of range (e.g. 0)
*  `end` = end of range (e.g. 10)
*  `step` = how many steps in between each value (e.g. 1)
> Note: In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

In [41]:
zero_to_ten = torch.range(0,10)
zero_to_ten

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input = zero_to_ten , dtype = torch.float16 , device = 'cpu')
ten_zeros , ten_zeros.device , ten_zeros.ndim

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float16),
 device(type='cpu'),
 1)

In [44]:
x = torch.tensor([[1,2,3] , [4,5,6]])
x.dtype , x.ndim , x.shape

(torch.int64, 2, torch.Size([2, 3]))

In [45]:
x[1][2]

tensor(6)

In [46]:
# Returns a view of a matrix (2-D tensor) conjugated and transposed.
x.H

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [47]:
# Returns a view of this tensor with the last two dimensions transposed.

# x.mT is equivalent to x.transpose(-2, -1).
x.mT

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## tensor datatype

In [48]:
# Default datatype for tensors is float32
data = torch.arange(0,5)
float_32_ten = torch.tensor(data , 
                           dtype = None ,
                           device = None ,
                           requires_grad = False)
float_32_ten

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


tensor([0, 1, 2, 3, 4])

In [49]:
import numpy as np

In [50]:
data = torch.tensor(np.array([[1,2,3],
                             [4,5,6]]))
data , data.ndim , data.shape , data.size() , data.dtype

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2,
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.int64)

In [51]:
data = torch.tensor([[1,2,3],
                     [4,5,6]])
# we note that the datatype is the same
data , data.ndim , data.shape , data.size() , data.dtype , data.device

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2,
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.int64,
 device(type='cpu'))

In [52]:
data = torch.tensor(np.array([[1,2,3],
                             [4,5,6]]), dtype = torch.float16)
data , data.ndim , data.shape , data.size() , data.dtype , data.device 

(tensor([[1., 2., 3.],
         [4., 5., 6.]], dtype=torch.float16),
 2,
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.float16,
 device(type='cpu'))

## Manupulation tensor (tensor operations)

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [53]:
tensor = torch.tensor([1,2,3,4])
tensor + 10 , print(f'the original tensor is {tensor}')

the original tensor is tensor([1, 2, 3, 4])


(tensor([11, 12, 13, 14]), None)

In [54]:
tensor * 10

tensor([10, 20, 30, 40])

In [55]:
# we can use function 
torch.multiply(tensor , 10)

tensor([10, 20, 30, 40])

## Matrix multiplication

In [56]:
tensor = torch.tensor([[1,2,3,4]])

In [57]:
tensor@tensor.T

tensor([[30]])

In [58]:
# by hand
%%time
value = 0 
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value

UsageError: Line magic function `%%time` not found.


In [59]:
%%time
torch.matmul(tensor , tensor.T)

CPU times: user 921 µs, sys: 148 µs, total: 1.07 ms
Wall time: 1.58 ms


tensor([[30]])

## stack tensors

In [60]:
# create a tensor 
x = torch.arange(1,8)
x  , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [61]:
# reshape the tensor 
x_reshaped = x.reshape(1,7)
x_reshaped , x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [62]:
# make a view for x tensor
z = x.view(1,7)
z , z.shape , z.ndim 

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]), 2)

In [63]:
# changing z change in x 
z[0][2] = 100
print(f'the new values of z are \n {z}')
print(f'the new values of x are \n {x}')

the new values of z are 
 tensor([[  1,   2, 100,   4,   5,   6,   7]])
the new values of x are 
 tensor([  1,   2, 100,   4,   5,   6,   7])


In [64]:
# stacke tensors on top of each other 
x_stacked = torch.stack([x,x,x,x])
x_stacked , x_stacked.shape , x_stacked.ndim

(tensor([[  1,   2, 100,   4,   5,   6,   7],
         [  1,   2, 100,   4,   5,   6,   7],
         [  1,   2, 100,   4,   5,   6,   7],
         [  1,   2, 100,   4,   5,   6,   7]]),
 torch.Size([4, 7]),
 2)

In [65]:
# stacke tensors on top of each other 
x_stacked = torch.stack([x,x,x,x] , dim=0)
x_stacked , x_stacked.shape , x_stacked.ndim

(tensor([[  1,   2, 100,   4,   5,   6,   7],
         [  1,   2, 100,   4,   5,   6,   7],
         [  1,   2, 100,   4,   5,   6,   7],
         [  1,   2, 100,   4,   5,   6,   7]]),
 torch.Size([4, 7]),
 2)

`torch.vstack()`

In [66]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

z = torch.vstack((a,b))
z , z.shape , z.ndim , z.dtype

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]),
 2,
 torch.int64)

`torch.hstack`

In [67]:
z_h = torch.hstack((a,b))
z_h , z_h.shape , z_h.ndim

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]), 1)

And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [68]:
x_reshaped.shape , x_reshaped.ndim

(torch.Size([1, 7]), 2)

In [69]:
# remove exstra dimention
print(f"we will remove this {x_reshaped.shape[0]} from {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
x_squeezed , x_squeezed.shape , x_squeezed.ndim

we will remove this 1 from torch.Size([1, 7])


(tensor([  1,   2, 100,   4,   5,   6,   7]), torch.Size([7]), 1)

In [70]:
# add exstra dimension with unsquessze
print(f"the original tensor {x_squeezed} and the shape is {x_squeezed.shape} and the dimention is {x_squeezed.ndim}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed , x_unsqueezed.shape , x_unsqueezed.ndim

the original tensor tensor([  1,   2, 100,   4,   5,   6,   7]) and the shape is torch.Size([7]) and the dimention is 1


(tensor([[  1,   2, 100,   4,   5,   6,   7]]), torch.Size([1, 7]), 2)

## pytorch tensor & numpy

In [71]:
import torch
import numpy as np

In [72]:
array = np.arange(1.0,10.0)
array , array.shape , array.ndim

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), (9,), 1)

In [73]:
# convert numpy arrat into tensor 
tensor = torch.from_numpy(array)
tensor ,tensor.shape , tensor.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 torch.Size([9]),
 1)

In [74]:
# any change happen  in array the tensor will not affected
print(f"the original array = {array}")
print(f" array + 1 = {array + 1}")
print(f"the original tensor = {tensor}")
print(f"doing operation on tensor+1=  {tensor+1}")

the original array = [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 array + 1 = [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
the original tensor = tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
doing operation on tensor+1=  tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)


## Reproducibility (trying to take the random out of random)

simply it is random seed

In [75]:
tensor_a = torch.rand(3,4)
print(f"tensor_a is = \n{tensor_a}")
tensor_b = torch.rand(3,4)
print(f"tensor_b is = \n{tensor_b}")

print("-"*40)

tensor_a == tensor_b

tensor_a is = 
tensor([[0.4922, 0.3346, 0.3326, 0.0632],
        [0.8520, 0.1457, 0.1994, 0.3276],
        [0.4071, 0.1404, 0.9416, 0.7702]])
tensor_b is = 
tensor([[0.4215, 0.9013, 0.0639, 0.3926],
        [0.3021, 0.1044, 0.9222, 0.1383],
        [0.3969, 0.1179, 0.2274, 0.8474]])
----------------------------------------


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [76]:
# to solve this problem
torch.manual_seed(seed = 42)
tensor_a = torch.rand(3,4)
print(f"tensor_a is = \n{tensor_a}")
torch.manual_seed(seed = 42)
tensor_b = torch.rand(3,4)
print(f"tensor_b is = \n{tensor_b}")

print("-"*40)

tensor_a == tensor_b

tensor_a is = 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor_b is = 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
----------------------------------------


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Looking at GPU

In [77]:
!nvidia-smi

Sun Aug 21 08:49:43 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## getting pytorch to run on the GPU

In [78]:
torch.cuda.is_available()

True

The output is `True` so we can use the GPU

In [79]:
# set device type
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [80]:
# count number of devices are availabel
torch.cuda.device_count()

1

## puting tensor & models on the GPU

In [81]:
# create a tensor (default on cpu)

tensor = torch.tensor([1,2,3])
print(f"before convert to gpu the original device {tensor.device}" )

tensor_on_gpu = tensor.to(device)
print(f"after convert to GPU {tensor_on_gpu.device}")
print(tensor_on_gpu)

before convert to gpu the original device cpu
after convert to GPU cuda:0
tensor([1, 2, 3], device='cuda:0')


In [82]:
# but there is a problem
# the problem is we can not convert the tensor to numpy array
tensor_on_gpu_array = tensor_on_gpu.array()

AttributeError: 'Tensor' object has no attribute 'array'

In [83]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
# now we convert it 
tensor_back_on_cpu 

array([1, 2, 3])

****Thanks torch doc****